// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDatabaseProject;

#nullable disable

namespace WebDatabaseProject.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20240522031430_EAV_V2")]
    partial class EAV_V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebDatabaseProject.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasDiscriminator<string>("Discriminator").IsComplete(false);
                });

            modelBuilder.Entity("WebDatabaseProject.BlogAttributeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogAttributeValues");
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.AttributeBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("BlogAttributes");

                    b.HasDiscriminator<int>("Type");
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.BoolAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.DateTimeAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.DecimalAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.IntegerAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.StringAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("WebDatabaseProject.EAV.UserAttribute", b =>
                {
                    b.HasBaseType("WebDatabaseProject.EAV.AttributeBase");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("WebDatabaseProject.BlogAttributeValue", b =>
                {
                    b.HasOne("WebDatabaseProject.EAV.AttributeBase", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDatabaseProject.Blog", null)
                        .WithMany("Configs")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("WebDatabaseProject.Blog", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
