// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDatabaseProject;

#nullable disable

namespace WebDatabaseProject.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20240306015748_AddHierarchyBlogs")]
    partial class AddHierarchyBlogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebDatabaseProject.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasDiscriminator<string>("Discriminator").IsComplete(false).HasValue("Blog");
                });

            modelBuilder.Entity("WebDatabaseProject.CareerBlog", b =>
                {
                    b.HasBaseType("WebDatabaseProject.Blog");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CareerBlog");
                });

            modelBuilder.Entity("WebDatabaseProject.TechBlog", b =>
                {
                    b.HasBaseType("WebDatabaseProject.Blog");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("TechBlog");
                });
#pragma warning restore 612, 618
        }
    }
}
